### ISSUE TITLE
Add this into HACs Feature request 

### ISSUE THREAD

**Issue by markmghali** [arturzx/homeassistant-iqua-softener#1]
Can you structure this so I can add it as a custom repository into HACs? Super excited to try this after I get it setup.
Thank you for the hard work

**Comment by arturzx** [comment]
This can be run after adding as custom repository in HACS, tested before publish. I don't know how to add this to official HACS repository list, maybe you know?

**Comment by markmghali** [comment]
Here is what I found on how to be in the default list https://hacs.xyz/docs/publish/start

**Comment by markmghali** [comment]
Ok I got it into HACs! Restarting home assistant now! Looking forward to this thank you

**Comment by cromefire** [comment]
> This can be run after adding as custom repository in HACS, tested before publish. I don't know how to add this to official HACS repository list, maybe you know?

Getting it into the HACS default list seems to be rather easy: https://hacs.xyz/docs/publish/include. Would be great to have it in HACS for easier discovery and it's only 2 GitHub actions, a proper icon and a PR.
