### ISSUE TITLE
Rheem water softener 

### ISSUE THREAD

**Issue by markmghali** [arturzx/homeassistant-iqua-softener#2]
Added my rheem water softener and a device is not showing up 

![Screenshot_20220816-065552.png](https://user-images.githubusercontent.com/17356528/184873731-8473f938-b633-44ac-aef9-0054dc03669f.png)

![Screenshot_20220816-064639~2.png](https://user-images.githubusercontent.com/17356528/184873254-3b7193e1-3d43-4ebe-978c-e22b86fb9c98.png)

This is the app I am using
![Screenshot_20220816-065754.png](https://user-images.githubusercontent.com/17356528/184874173-6fd31af2-52ba-4da2-9d32-34f688b6636a.png)

Is this only for ecowater brand?

**Comment by arturzx** [comment]
Ecowater have separate API and integration (https://hacs.xyz/docs/repositories/integration/barleybobs_homeassistant_ecowater_softener). I have Viessmann Duo Smart, this is Ecowater OEM and works with iQua app. Can you check HA logs for some errors? Have you double checked entered data?

**Comment by markmghali** [comment]
Ok! I got it figured out. Username is in email format. Didn't have the @
initially! Shows everything now! So excited to have this in home assistant!
Thank you again
