### ISSUE TITLE
AquaHome 20 Smart

### ISSUE THREAD

**Issue by gigipawel** [arturzx/homeassistant-iqua-softener#3]
Hej!
Czy aplikacja bedzie działać z AquaHome 20 Smart ?

**Comment by szymonplotkowski** [comment]
Yep! It works like a charm. 
Właśnie chwilę temu wbiłem go do swojego HASS. Mam tylko mały problem z dopisaniem go do dashboard Energy, ale już nad tym pracuję.

**Comment by gigipawel** [comment]
U mnie też. Zaciagniete przez Gita nie trzabyło Samby używać :) 
Dziękie pięknie autorowi ! 

Szymon daj znać jak obsłużysz go w Energy co poprawić :)

**Comment by szymonplotkowski** [comment]
Na razie nie energy, ale zacznij od wyłączenia w HASS lub wyrzucenia z kodu sensor.date_time. Niepotrzebnie pluje danymi.

**Comment by gigipawel** [comment]
I przydało by się żeby data się wyświetlała zamiast "w Zeszłym tyg" w Last regeneration .

**Comment by arturzx** [comment]
> Hej! Czy aplikacja bedzie działać z AquaHome 20 Smart ?

Pewnie tak, mam Aquahome Duo Smart ale to jedno i to samo, w środku jest ESP32 który wysyła po MQTT dane na zdefiniowany serwer, w przypadku Viessmanna to na serwery aplikacji iQua które są w Amazonie. Próbowałem rozkminić jak podmienić konfigurację żeby wysyłać to na lokalny serwer ale coś mi nie działało a później już nie miałem czasu się tym bawić.

> I przydało by się żeby data się wyświetlała zamiast "w Zeszłym tyg" w Last regeneration .

No właśnie to HA tak prezentuje dane w formie timestampa, można by tą encję teorytycznie zrobić typu znakowego i wrzucać tam datę.

> Mam tylko mały problem z dopisaniem go do dashboard Energy, ale już nad tym pracuję.

W jakim celu go dopisywać do dashboarda energy? Którą encję?

**Comment by szymonplotkowski** [comment]
Dopisując encję z chwilowym zużyciem lub z użyciem z całego dnia mamy
możliwość mnożenia przez cenę (pobieraną z jeszcze innej encji lub wbitą na
twardo), by estymować wartość rachunku.

czw., 3 lis 2022, 21:00 użytkownik arturzx ***@***.***>
napisał:

**Comment by arturzx** [comment]
> Dopisując encję z chwilowym zużyciem lub z użyciem z całego dnia mamy możliwość mnożenia przez cenę (pobieraną z jeszcze innej encji lub wbitą na twardo), by estymować wartość rachunku

@szymonplotkowski dzięki, myślałem, że ten dashboard dotyczy tylko energii elektrycznej/gazu.

**Comment by laziukiewicz** [comment]
@arturzx w wersji 2022.11 dodano śledzenie zużycia wody. Też jestem bardzo zainteresowany podpięciem do dashboardu statystyk z tej integracji.

**Comment by arturzx** [comment]
@laziukiewicz @szymonplotkowski @gigipawel zaktualizowałem sensory i można już ich używać w dashboardzie Energy. Niestety wymagało to zmiany jednostek z litrów na m3 bo z tego co widzę ten dashboard oczekuje m3 albo galonów.
